AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: |
  A RESTful service for posting lead emails

Resources:
  LeadsPostHandler:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs8.10
      Handler: server.leadsPostHandler
      Events:
        ListCustomers:
          Type: Api
          Properties:
            Path: /leads
            Method: post
