AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: |
  An example RESTful service

Resources:
  GetHandler:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs8.10
      Handler: server.getHandler
      Events:
        ListCustomers:
          Type: Api
          Properties:
            Path: /
            Method: get
  PostHandler:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs8.10
      Handler: server.postHandler
      Events:
        ListCustomers:
          Type: Api
          Properties:
            Path: /
            Method: post
